### ISSUE TITLE
Přidání češtiny na Weblate

### ISSUE THREAD

**Issue by flaiming** [madnest/flarum-lang-czech#4]
Pro přístupnější překlad Flara do češtiny by bylo dobré přidat český překlad na [Weblate](https://weblate.rob006.net/projects/flarum/), kde jsou i ostatní překlady. Čeština tam ale zatím není zaločená, ale @madnest by to tam mohl založit, viz návod na https://github.com/rob006-software/flarum-translations/wiki .

**Comment by repl6669** [comment]
Zalozim to tam, uz jsem se na to dival, urcite by to bylo lepsi. Super, ze jsme pockali na v1.

**Comment by ghost** [comment]
Zrovna jsem to zde chtěl napsat a předběhli jste mě. Jsem pro, usnadní to překlad a může se připojit více překladatelů.
Už tam mám účet, takže jen čekám na přidání.

**Comment by repl6669** [comment]
Jdu na to, konečně mám chvilku. Dám echo.

EDIT: Done, tak snad to brzy vyřeší a můžeme se pustit do díla.

**Comment by ghost** [comment]
Super, tuším že většina frází jsou totožná a stačí doplnit jen minimální množství frází na překlad.
Takhle verze překladu byla stará, nešli překládat fráze jako seconds ago, day ago apod. Protože se změnil typ souboru a nacházeli se v configu a proto nešli překládat např. pomocí FoF Linguist, v novější verzi překladu jsou tyto fráze již v yml souboru pokud se nepletu.

**Comment by repl6669** [comment]
Snad to tak bude. Uvidíme, jak se s tím popere ten bot, ale v ideálním případě to bude tak, jak říkáte.

**Comment by ghost** [comment]
Tak čeština je přidána - https://weblate.rob006.net/projects/flarum/#languages

**Comment by ghost** [comment]
Tak většina frází přeložena (momentálně 97%), dopřeložil jsem i pár pluginu od FoF. U některých frází jsem si nebyl jistý, konkrétně (Slug driver aj. viz přeposláno ke kontrole na weblate). Občas využívám pro překlad složitějších frází https://www.deepl.com/translator nabízí mnohem lepší výsledný překlad než klasický translator od Googlu.

Prošel jsem všech 444 frází, u pár jsem našel chybku tak to jsem opravil a u některých jsem navrhl lepší překlad, který zle vidět v části ke schválení. Nenašel jsem v textu ale fráze jako second ago, hour ago, minute apod. zkrátka tyto časové údaje, které se nachází v souboru config.js ovšem jak už jsem psal v nejnovější verzi překladu EN by měli být součástí souboru dayjs a proto je lze také přeložit i ve FlarumFree, na kterém provozuju pár projektů. Tyto časové fráze se již nenachází v souboru config.js ale v dayjs (https://discuss.flarum.org/d/25196-beta-14-dayjs-translations)  

Dokud tam nebudou přidány nepůjdou na FlarumFree přeložit díky FoF Linguist proto prosím o kontrolu. Jinak se zdá vše hotovo.

**Comment by repl6669** [comment]
Vyměnil jsem momentjs za dayjs. Ještě si ověřím správnost na základě jiných translation packages.

Jinak DeepL je super, četl jsem o tom onehdá článek.

**Comment by repl6669** [comment]
Celé jsem to prošel a vše approvenul, tu a tam něco poupravil a doplnil nepřeložené fráze. Až dojde k celkové synchronizaci ca za hodinu, tak tagnu verzi 1.

**Comment by ghost** [comment]
Super díky moc !

**Comment by ghost** [comment]
Tak mě čeština funguje (vyzkoušeno na Flarum). Kromě tehle chybky opakujicího se textu (asi neni ok že ?) jsem si zatím ničeho nevšiml. 
Na verzi FreeFlarum otestuju až to tam nahodí správce. 
![111](https://user-images.githubusercontent.com/83711979/120823151-6d35c880-c557-11eb-8de4-8a7747a43f20.jpg)

**Comment by repl6669** [comment]
Mrknu na to a zkusím to opravit podle třeba polského překladu.

**Comment by ghost** [comment]
No nějak se to tam opakuje moc. Já si to změnil v Linguist.
Každopádně to už jsou maličkosti.

Originál
![02242](https://user-images.githubusercontent.com/83711979/120836613-0d92e980-c566-11eb-9963-c28609f1828b.JPG)


Změněná verze
![0121](https://user-images.githubusercontent.com/83711979/120836571-010e9100-c566-11eb-966e-5aea25f7efd3.JPG)

Výsledek
![4454](https://user-images.githubusercontent.com/83711979/120836649-15eb2480-c566-11eb-8725-f71ceaf38c6f.JPG)

**Comment by repl6669** [comment]
Myslím, že tou vaší úpravou ztratíme singular vs plural, upravil jsem to trošku jinak. Mohu se zeptat, proč nevytvoříte suggestions přímo ve Weblate? Přece proto jsem to tam založil - abychom na překladu mohli spolupracovat.
